// This program demonstrates how a pointer can be used as an array in C++.

#include <iostream>

using namespace std;

int main()
{
    char strng[60] = "Rule #1 Always wear a suit. - Barney Stinson";		// Create a String.
    char *pntr;		            // Create a Pointer.

    pntr = strng;    	        // Make the pointer point to the base of the String (str[0]).

    cout << pntr[5] << endl;	// Print the 5th character of the string, using the pointer like an array.
    cout << pntr << endl;	    // Print the entire string using the pointer.

    return 0;
}
